spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/kotlin
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: ghdcoalss33
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true

slack:
    test:
        url: private

naver:
    top:
        stock:
            url: https://api.finance.naver.com/service/mainSummary.naver?_callback=window.__jindo2_callback._5987
