spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/kotlin
        driver-class-name: org.mariadb.jdbc.Driver
        username: root
        password: ghdcoalss33
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true

slack:
    test:
        url: private
