spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
        show-sql: true


slack:
    test:
        url: https://hooks.slack.com/services/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

naver:
    top:
        stock:
            url: https://api.finance.naver.com/service/mainSummary.naver?_callback=window.__jindo2_callback._5987

server:
    port: 8080
