spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
        show-sql: true


naver:
    top:
        stock:
            url: https://api.finance.naver.com/service/mainSummary.naver?_callback=window.__jindo2_callback._5987

m:
    naver:
        stock:
            main: https://m.stock.naver.com/api/home/majors

server:
    port: 1203
